require 'pry'
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

survivor = TelevisionShow.find_or_create_by(name: "Survivor")
big_brother = TelevisionShow.find_or_create_by(name: "Big Brother")

survivor_seasons = [
  ["Borneo", "May 31, 2000", "August 23, 2000", 1],
  ["The Australian Outback", "January 28, 2001", "May 3, 2001", 2],
  ["Africa", "October 11, 2001", "January 10, 2002", 3],
  ["Marquesas", "February 28, 2002", "May 19, 2002", 4],
  ["Thailand", "September 19, 2002", "December 19, 2002", 5],
  ["The Amazon", "February 13, 2003", "May 11, 2003", 6],
  ["Pearl Islands", "September 18, 2003", "December 14, 2003", 7],
  ["All-Stars", "February 1, 2004", "May 9, 2004", 8],
  ["Vanuatu", "September 16, 2004", "December 12, 2004", 9],
  ["Palau", "February 17, 2005", "May 15, 2005", 10],
  ["Guatemala", "September 15, 2005", "December 11, 2005", 11],
  ["Panama", "February 2, 2006", "May 14, 2006", 12],
  ["Cook Islands", "September 14, 2006", "December 17, 2006", 13],
  ["Fiji", "February 8, 2007", "May 13, 2007", 14],
  ["China", "September 20, 2007", "December 16, 2007", 15],
  ["Micronesia", "February 7, 2008", "May 11, 2008", 16],
  ["Gabon", "September 25, 2008", "December 14, 2008", 17],
  ["Tocantins", "February 12, 2009", "May 17, 2009", 18],
  ["Samoa", "September 17, 2009", "December 20, 2009", 19],
  ["Heroes vs. Villains", "February 11, 2010", "May 16, 2010", 20],
  ["Nicaragua", "September 15, 2010", "December 19, 2010", 21],
  ["Redemption Island", "February 16, 2011", "May 15, 2011", 22],
  ["South Pacific", "September 14, 2011", "December 18, 2011", 23],
  ["One World", "February 15, 2012", "May 13, 2012", 24],
  ["Phillippines", "September 19, 2012", "December 16, 2012", 25],
  ["Caramoan", "February 13, 2013", "May 12, 2013", 26],
  ["Blood vs. Water", "September 18, 2013", "December 15, 2013", 27],
  ["Cagayan", "February 26, 2014", "May 21, 2014", 28],
  ["San Juan del Ser", "September 24, 2014", "December 17, 2014", 29],
  ["Worlds Apart", "February 25, 2015", "May 20, 2015", 30],
  ["Cambodia", "September 23, 2015", "December 16, 2015", 31],
  ["Kaôh Rōng", "February 17, 2016", "May 18, 2016", 32],
  ["Millennials vs. Gen X", "September 21, 2016", "December 14, 2016", 33],
  ["Game Changers", "March 8, 2017", "May 24, 2017", 34],
  ["Heroes vs. Healers vs. Hustlers", "September 27, 2017", "December 20, 2017", 35],
  ["Ghost Island", "February 28, 2018", "May 23, 2018", 36],
  ["David vs. Goliath", "September 26, 2018", "", 37]
]

big_brother_seasons = [
  ["Big Brother 1", "July 5, 2000", "September 29, 2000", 1],
  ["Big Brother 2", "July 5, 2001", "September 20, 2001", 2],
  ["Big Brother 3", "July 10, 2002", "September 25, 2002", 3],
  ["Big Brother 4", "July 8, 2003", "September 24, 2003", 4],
  ["Big Brother 5", "July 6, 2004", "September 21, 2004", 5],
  ["Big Brother 6", "July 7, 2005", "September 20, 2005", 6],
  ["Big Brother All Stars", "July 6, 2006", "September 12, 2006", 7],
  ["Big Brother 8", "July 5, 2007", "September 18, 2007", 8],
  ["Big Brother 9", "February 12, 2008", "April 27, 2008", 9],
  ["Big Brother 10", "July 13, 2008", "September 16, 2008", 10],
  ["Big Brother 11", "July 9, 2009", "September 15, 2009", 11],
  ["Big Brother 12", "July 8, 2010", "September 15, 2010", 12],
  ["Big Brother 13", "July 7, 2011", "September 14, 2011", 13],
  ["Big Brother 14", "July 12, 2012", "September 19, 2012", 14],
  ["Big Brother 15", "June 26, 2013", "September 18, 2013", 15],
  ["Big Brother 16", "June 25, 2014", "September 24, 2014", 16],
  ["Big Brother 17", "June 24, 2015", "September 23, 2015", 17],
  ["Big Brother 18", "June 22, 2016", "September 21, 2016", 18],
  ["Big Brother 19", "June 28, 2017", "September 20, 2017", 19],
  ["Big Brother 20", "June 27, 2018", "September 26, 2018", 20]
]

survivor_seasons.each do |ss|
  Season.find_or_create_by(name: ss[0],
                start_date: ss[1],
                end_date: ss[2],
                season_number: ss[3],
                television_show_id: survivor.id
               )
end

big_brother_seasons.each do |bb|
  Season.find_or_create_by(name: bb[0],
                start_date: bb[1],
                end_date: bb[2],
                season_number: bb[3],
                television_show_id: big_brother.id
               )
end

contestants = {
  # Season_Number:
  # "Name": [Birthday,
  #          Day Out,
  #          Votes Against,
  #          Tribe Name,
  #          Jury (Boolean),
  #          Merged (Boolean)]
  "survivor":  {
    "1": {
      "Richard Hatch":      "April 8",
      "Kelly Wigglesworth": "June 24",
      "Rudy Boesch":        "January 20",
      "Susan Hawk":         "August 17",
      "Sean Kenniff":       "November 27",
      "Colleen Haskell":    "December 6",
      "Gervase Peterson":   "November 2",
      "Jenna Lewis":        "July 16",
      "Greg Buis":          "December 31",
      "Gretchen Cordy":     "February 7",
      "Joel Klug":          "April 13",
      "Dirk Been":          "June 15",
      "Ramona Gray":        "January 20",
      "Stacey Stillman":    "August 11",
      "B.B Anderson":       "January 18",
      "Sonja Christopher":  "January 28",
    },
    "2": {
      "Tina Wesson":        "December 26",
      "Colby Donaldson":    "April 1",
      "Keith Famie":        "February 11",
      "Elisabeth Filarski": "May 28",
      "Rodger Bingham":     "July 5",
      "Amber Brkich":       "August 11",
      "Nick Brown":         "April 2",
      "Jerri Manthey":      "September 5",
      "Alicia Calaway":     "May 1",
      "Jeff Varner":        "April 16",
      "Michael Skupin":     "January 29",
      "Kimmi Kappenburg":   "November 11",
      "Mitchell Olsen":     "March 17",
      "Maralyn Hershey":    "January 24",
      "Kel Gleason":        "January 5",
      "Debb Eaton":         "June 11",
    },
    "3": {
      "Ethan Zohn":         "November 12",
      "Kim Johnson":        "September 18",
      "Lex van der Berghe": "June 18",
      "Tom Buchanan":       "October 30",
      "Teresa Cooper":      "May 5",
      "Kim Powers":         "December 3",
      "Frank Garrison":     "July 22",
      "Brandon Quinton":    "January 22",
      "Kelly Goldsmith":    "April 27",
      "Clarence Black":     "December 21",
      "Lindsay Richter":    "August 31",
      "Silas Gaither":      "January 28",
      "Linda Spencer":      "January 1",
      "Carl Bilancione":    "June 20",
      "Jessie Camacho":     "September 24",
      "Diane Ogden":        "April 27"
    },
    "4": {
      "Vecepia Towery":             "December 9",
      "Neleh Dennis":               "February 19",
      "Kathy Vavrick-O'Brien":      "January 6",
      "Paschal English":            "March 5",
      "Sean Rector":                "August 20",
      "Robert DeCanio":             "June 19",
      "Tammy Leitner":              "July 3",
      "Zoe Zanidakis":              "March 17",
      "John Carroll":               "June 14",
      "Rob Mariano":                "December 25",
      "Gina Crews":                 "February 7",
      "Gabriel Cade":               "July 1",
      "Sarah Jones":                "August 11",
      "Hunter Ellis":               "July 5",
      "Patricia Jackson":           "April 8",
      "Peter Harkey":               "January 17"
    },
    "5":                            {
      "Brian Heidik":               "March 9",
      "Clay Jordan":                "December 30",
      "Jan Gentry":                 "October 31",
      "Helen Glover":               "April 28",
      "Ted Rogers, Jr":             "December 28",
      "Jake Billingsley":           "August 21",
      "Penny Ramsey":               "April 24",
      "Ken Stafford":               "June 20",
      "Erin Collins":               "January 7",
      "Shii Ann Huang":             "January 24",
      "Robb Zbacnik":               "September 12",
      "Stephanie Dill":             "November 15",
      "Ghandia Johnson":            "Janaury 3",
      "Jed Hildebrand":             "December 5",
      "Tanya Vance":                "November 29",
      "John Raymond":               "February 21"
    },
    "6":                            {
      "Jenna Morasca":              "February 15",
      "Matthew von Ertfelda":       "July 24",
      "Rob Cesternino":             "October 20",
      "Butch Lockley":              "August 28",
      "Heidi Strobel":              "October 29",
      "Christy Smith":              "September 13",
      "Alex Bell":                  "May 16",
      "Deena Bennett":              "February 12",
      "Dave Johnson":               "January 16",
      "Roger Sexton":               "September 26",
      "Shawna Mitchell":            "July 28",
      "Jeanne Hebert":              "January 6",
      "JoAnna Ward":                "April 29",
      "Daniel Lue":                 "November 29",
      "Janet Koth":                 "November 18",
      "Ryan Aiken":                 "February 13"
    },
    "7":                            {
      "Sandra Diaz-Twine":          "July 30",
      "Lillian Morris":             "April 3",
      "Jon Dalton":                 "March 11",
      "Darrah Johnson":             "May 19",
      "Burton Roberts":             "April 10",
      "Christa Hastie":             "November 6",
      "Tijuana Bradley":            "July 23",
      "Rupert Boneham":             "January 27",
      "Ryan Opray":                 "August 6",
      "Andrew Savage":              "July 29",
      "Osten Taylor":               "December 10",
      "Shawn Cohen":                "September 20",
      "Trish Dunn":                 "October 29",
      "Michelle Tesauro":           "January 16",
      "Ryan Shoulders":             "March 28",
      "Nicole Delma":               "September 19"
    },
    "8":                            {
      "Amber Brkich":               "August 11",
      "Rob Mariano":                "December 25",
      "Jenna Lewis":                "July 16",
      "Rupert Boneham":             "January 27",
      "Tom Buchanan":               "October 30",
      "Shii Ann Huang":             "January 24",
      "Alicia Calaway":             "May 1",
      "Kathy Vavrick-O'Brien":      "January 6",
      "Lex van der Berghe":         "June 18",
      "Jerri Manthey":              "September 5",
      "Ethan Zohn":                 "November 12",
      "Colby Donaldson":            "April 1",
      "Susan Hawk":                 "August 17",
      "Richard Hatch":              "April 8",
      "Rob Cesternino":             "October 20",
      "Jenna Morasca":              "February 15",
      "Rudy Boesch":                "January 20",
      "Tina Wesson":                "December 26"
    },
    "9":                            {
      "Chris Daugherty":            "August 29",
      "Twila Tanner":               "October 12",
      "Scout Cloud Lee":            "November 8",
      "Eliza Orlins":               "December 25",
      "Julie Berry":                "December 15",
      "Ami Cusack":                 "January 25",
      "Leann Slaby":                "July 8",
      "Chad Crittenden":            "August 8",
      "Lea Masters":                "March 28",
      "Rory Freeman":               "October 30",
      "John Kenney":                "September 26",
      "Lisa Keiffer":               "May 3",
      "Travis Sampson":             "February 19",
      "Brady Finta":                "December 17",
      "Mia Galeotalanza":           "August 17",
      "John Palyok":                "May 13",
      "Dolly Neely":                "November 18",
      "Brook Geraghty":             "November 20"
    },
    "10":                           {
      "Tom Westman":                "January 4",
      "Katie Gallagher":            "May 28",
      "Ian Rosenberger":            "August 24",
      "Jenn Lyon":                  "February 27",
      "Caryn Groedel":              "August 13",
      "Gregg Carey":                "January 9",
      "Stephenie LaGrossa":         "December 6",
      "Janu Tornell":               "May 9",
      "Coby Archa":                 "September 8",
      "Bobby Jon Drinkard":         "May 10",
      "Ibrehem Rahman":             "March 4",
      "James Miller":               "July 8",
      "Angie Jakusz":               "March 27",
      "Willard Smith":              "November 30",
      "Kim Mullen":                 "March 13",
      "Jeff Wilson":                "February 9",
      "Ashlee Ashby":               "May 2",
      "Jolanda Jones":              "November 6",
      "Wanda Shirk":                "August 24",
      "Jonathan Libby":             "September 5"
    },
    "11":                           {
      "Danni Boatwright":           "July 13",
      "Stephenie LaGrossa":         "December 6",
      "Rafe Judkins":               "January 8",
      "Lydia Morales":              "January 19",
      "Cindy Hall":                 "June 28",
      "Judd Sergeant":              "September 13",
      "Jamie Newton":               "January 26",
      "Bobby Jon Drinkard":         "May 10",
      "Brandon Bellinger":          "January 22",
      "Amy O'Hara":                 "November 2",
      "Brian Corridan":             "February 10",
      "Margaret Bobonich":          "June 5",
      "Blake Towsley":              "May 5",
      "Brooke Struck":              "July 30",
      "Brianna Varela":             "October 29",
      "Morgan McDevitt":            "November 24",
      "Jim Lynch":                  "January 7"
    },
    "12":                           {
      "Aras Baskauskas":            "September 26",
      "Danielle DiLorenzo":         "June 3",
      "Terry Deitz":                "October 10",
      "Cirie Fields":               "July 18",
      "Shane Powers":               "November 28",
      "Courtney Marit":             "May 24",
      "Bruce Kanegai":              "December 17",
      "Sally Schumann":             "December 10",
      "Austin Carty":               "April 29",
      "Nick Stanbury":              "July 21",
      "Dan Barry":                  "December 30",
      "Bobby Mason":                "August 20",
      "Ruth-Marie Milliman":        "April 11",
      "Misty Giles":                "February 25",
      "Melinda Hyder":              "May 23",
      "Tina Scheer":                "November 17"
    },
    "13":                           {
      "Yul Kwon":                   "February 14",
      "Ozzy Lusth":                 "August 23",
      "Becky Lee":                  "September 11",
      "Sundra Oakley":              "January 2",
      "Adam Gentry":                "August 21",
      "Parvati Shallow":            "September 21",
      "Jonathan Penner":            "March 5",
      "Candice Cody":               "November 12",
      "Nate Gonzalez":              "July 26",
      "Jenny Guzon-Bae":            "May 8",
      "Rebecca Borman":             "August 31",
      "Brad Virata":                "November 23",
      "Jessica Smith":              "January 22",
      "Cristina Coria":             "April 18",
      "Cao Boi Bui":                "April 10",
      "Stephannie Favor":           "July 12",
      "J.P. Calderon":              "September 5",
      "Cecilia Mansilla":           "January 13",
      "Billy Garcia":               "April 22",
      "Sekou Bunch":                "September 9"
    },
    "14":                           {
      "Earl Cole":                  "April 9",
      "Dreamz Herd":                "December 15",
      "Cassandra Franklin":         "April 19",
      "Yau-Man Chan":               "August 26",
      "Boo Bernis":                 "June 21",
      "Stacy Kimball":              "October 1",
      "Alex Angarita":              "April 20",
      "Mookie Lee":                 "November 10",
      "Edgardo Rivera":             "October 5",
      "Michelle Yi":                "December 2",
      "Lisi Linares":               "June 9",
      "Rocky Reid":                 "September 11",
      "Anthony Robinson":           "June 25",
      "Rita Verreos":               "July 19",
      "Liliana Gomez":              "April 5",
      "Gary Stritesky":             "September 16",
      "Sylvia Kwan":                "August 18",
      "Erica Durousseau":           "December 11",
      "Jessica deBen":              "April 25"
    },
    "15":                           {
      "Todd Herzog":                "January 29",
      "Courtney Yates":             "March 26",
      "Amanda Kimmel":              "August 3",
      "Denise Martin":              "May 5",
      "Peih-Gee Law":               "April 7",
      "Erik Huffman":               "January 31",
      "James Clement":              "March 9",
      "Frosti Zernow":              "February 15",
      "Jean-Robert Bellande":       "September 17",
      "Jaime Dugan":                "June 30",
      "Sherea Lloyd":               "July 31",
      "Aaron Reisberger":           "April 25",
      "Dave Cruser":                "October 26",
      "Leslie Nease":               "March 25",
      "Ashley Massaro":             "May 26",
      "Chicken Morris":             "September 2"
    },
    "16":                           {
      "Parvati Shallow":            "September 21",
      "Amanda Kimmel":              "August 3",
      "Cirie Fields":               "July 18",
      "Natalie Bolton":             "December 31",
      "Erik Reichenbach":           "November 27",
      "Alexis Jones":               "July 6",
      "James Clement":              "March 9",
      "Jason Siska":                "March 4",
      "Ozzy Lusth":                 "August 23",
      "Eliza Orlins":               "December 25",
      "Ami Cusack":                 "January 25",
      "Tracy Hughes-Wolf":          "July 9",
      "Kathy Sleckman":             "August 14",
      "Chet Welch":                 "October 22",
      "Jonathan Penner":            "March 5",
      "Joel Anderson":              "June 1",
      "Mikey Bortone":              "December 29",
      "Yau-Man Chan":               "August 26",
      "Mary Sartain":               "November 11",
      "Jon Dalton":                 "March 11"
    },
    "17":                           {
      "Bob Crowley":                "February 25",
      "Susie Smith":                "October 24",
      "Sugar Kiper":                "February 22",
      "Matty Whitmore":             "December 18",
      "Ken Hoang":                  "October 10",
      "Crystal Cox":                "March 28",
      "Corinne Kaplan":             "January 17",
      "Randy Bailey":               "March 31",
      "Charlie Herschel":           "May 12",
      "Marcus Lehman":              "October 3",
      "Dan Kay":                    "June 30",
      "Ace Gordon":                 "September 3",
      "Kelly Czarnecki":            "April 4",
      "G.C. Brown":                 "July 13",
      "Jacquie Berg":               "September 10",
      "Paloma Soto-Castillo":       "August 24",
      "Gillian Larson":             "February 24",
      "Michelle Chase":             "March 7"
    },
    "18":                           {
      "J.T. Thomas":                "June 23",
      "Stephen Fishbach":           "January 24",
      "Erinn Lobdell":              "October 21",
      "Taj Johnson-George":         "April 29",
      "Coach Wade":                 "September 18",
      "Debbie Beebe":               "September 28",
      "Sierra Reed":                "September 29",
      "Tyson Apostol":              "June 17",
      "Brendan Synnott":            "September 28",
      "Joe Dowdle":                 "July 29",
      "Sydney Wheeler":             "May 11",
      "Spencer Duhm":               "December 20",
      "Sandy Burgin":               "July 1",
      "Jerry Sims":                 "May 18",
      "Candace Smith":              "February 1",
      "Carolina Eastwood":          "October 27"
    },
    "19":                           {
      "Natalie White":              "April 22",
      "Russell Hantz":              "October 10",
      "Mick Trimming":              "May 10",
      "Brett Clouser":              "December 27",
      "Jaison Robinson":            "September 25",
      "Shambo Waters":              "April 25",
      "Monica Padilla":             "July 14",
      "Dave Ball":                  "August 13",
      "John Fincher":               "August 16",
      "Laura Morett":               "July 30",
      "Kelly Sharbaugh":            "December 26",
      "Erik Cardona":               "April 13",
      "Liz Kim":                    "November 24",
      "Russell Swan":               "February 17",
      "Ashley Trainer":             "February 27",
      "Yasmin Giles":               "August 29",
      "Ben Browning":               "August 28",
      "Betsy Bolan":                "March 20",
      "Mike Borassi":               "March 13",
      "Marisa Calihan":             "July 26"
    },
    "20":                           {
      "Sandra Diaz-Twine":          "July 30",
      "Parvati Shallow":            "September 21",
      "Russell Hantz":              "October 10",
      "Jerri Manthey":              "September 5",
      "Colby Donaldson":            "April 1",
      "Rupert Boneham":             "January 27",
      "Danielle DiLorenzo":         "June 3",
      "Candice Woodcock":           "November 12",
      "Amanda Kimmel":              "August 3",
      "J.T. Thomas":                "June 23",
      "Courtney Yates":             "March 26",
      "Coach Wade":                 "September 18",
      "Rob Mariano":                "December 25",
      "James Clement":              "March 9",
      "Tyson Apostol":              "June 17",
      "Tom Westman":                "January 4",
      "Cirie Fields":               "July 18",
      "Randy Bailey":               "March 31",
      "Stephenie LaGrossa":         "December 6",
      "Sugar Kiper":                "February 22"
    },
    "21":                           {
      "Fabio Birza":                "June 12",
      "Chase Rice":                 "September 19",
      "Sash Lenahan":               "November 22",
      "Holly Hoffman":              "March 13",
      "Dan Lembo":                  "November 5",
      "Jane Bright":                "December 13",
      "Benry Henry":                "June 25",
      "Kelly Shinn":                "May 5",
      "NaOnka Mixon":               "February 17",
      "Brenda Lowe":                "November 3",
      "Marty Piombo":               "November 11",
      "Alina Wilson":               "February 20",
      "Jill Behm":                  "January 18",
      "Yve Rojas":                  "March 9",
      "Kelly Bruno":                "March 23",
      "Tyrone Davis":               "September 24",
      "Jimmy Tarantino":            "September 7",
      "Jimmy Johnson":              "July 16",
      "Shannon Elkins":             "December 4",
      "Wendy DeSmidt-Kohlhoff":     "December 13"
    },
    "22":                           {
      "Rob Mariano":                "December 25",
      "Phillip Sheppard":           "March 12",
      "Natalie Tenerelli":          "May 6",
      "Ashley Underwood":           "February 8",
      "Andrea Boehlke":             "May 10",
      "Matt Elrod":                 "October 2",
      "Mike Chiesl":                "September 15",
      "Grant Mattos":               "March 12",
      "Ralph Kiser":                "October 27",
      "Steve Wright":               "April 8",
      "Julie Wolfe":                "May 11",
      "David Murphy":               "July 16",
      "Sarita White":               "October 2",
      "Stephanie Valencia":         "February 3",
      "Krista Klumpp":              "July 7",
      "Kristina Kell":              "December 26",
      "Russell Hantz":              "October 10",
      "Francesca Hogi":             "November 3"
    },
    "23":                           {
      "Sophia Clarke":              "July 10",
      "Coach Wade":                 "September 18",
      "Albert Destrade":            "March 31",
      "Ozzy Lusth":                 "August 23",
      "Rick Nelson":                "October 24",
      "Brandon Hantz":              "October 15",
      "Edna Ma":                    "August 22",
      "John Cochran":               "January 17",
      "Whitney Duncan":             "August 3",
      "Dawn Meehan":                "June 29",
      "Keith Tollefson":            "October 1",
      "Jim Rice":                   "September 14",
      "Christine Shields Markoski": "June 17",
      "Mikayla Wingle":             "May 31",
      "Elyse Umemoto":              "May 10",
      "Stacey Powell":              "November 21",
      "Mark Caruso":                "July 7",
      "Semhar Tadesse":             "September 12"
    },
    "24":                           {
      "Kim Spradlin":               "January 30",
      "Sabrina Thompson":           "March 6",
      "Chelsea Meissner":           "June 13",
      "Christina Cha":              "September 26",
      "Alicia Rosa":                "January 11",
      "Tarzan Smith":               "December 12",
      "Kat Edorsson":               "June 22",
      "Troyzan Robertson":          "July 30",
      "Lief Manson":                "February 1",
      "Jay Byars":                  "November 5",
      "Michael Jefferson":          "August 29",
      "Jonas Otsuji":               "March 25",
      "Colton Cumbie":              "November 22",
      "Monica Culpepper":           "June 15",
      "Bill Posley":                "September 28",
      "Matt Quinlan":               "April 5",
      "Nina Acosta":                "April 3",
      "Kourtney Moon":              "February 27"
    },
    "25":                           {
      "Denise Stapley":             "January 1",
      "Michael Skupin":             "January 29",
      "Lisa Whelchel":              "May 29",
      "Malcolm Freberg":            "May 7",
      "Abi-Maria Gomes":            "October 21",
      "Carter Williams":            "May 26",
      "Jonathan Penner":            "March 5",
      "Pete Yurkowski":             "March 3",
      "Artis Silvester":            "April 18",
      "Jeff Kent":                  "March 7",
      "RC Saint-Amour":             "May 10",
      "Katie Hanson":               "November 29",
      "Sarah Dawson":               "November 15",
      "Dana Lambert":               "December 13",
      "Russell Swan":               "February 17",
      "Angie Layton":               "October 8",
      "Roxy Morris":                "June 3",
      "Zane Knight":                "February 20"
    },
    "26":                           {
      "John Cochran":               "January 17",
      "Sherri Biethman":            "September 9",
      "Dawn Meehan":                "June 29",
      "Eddie Fox":                  "April 15",
      "Erik Reichenbach":           "November 27",
      "Brenda Lowe":                "November 3",
      "Andrea Boehlke":             "May 10",
      "Reynold Toepfer":            "October 6",
      "Malcolm Freberg":            "May 7",
      "Phillip Sheppard":           "March 12",
      "Michael Snow":               "August 30",
      "Corinne Kaplan":             "January 17",
      "Julia Landauer":             "November 12",
      "Matt Bischoff":              "April 4",
      "Brandon Hantz":              "October 15",
      "Laura Alexander":            "September 12",
      "Shamar Thomas":              "September 27",
      "Hope Driskill":              "July 6",
      "Allie Pohevitz":             "December 24",
      "Francesca Hogi":             "November 3"
    },
    "27":                           {
      "Tyson Apostol":              "June 17",
      "Monica Culpepper":           "June 15",
      "Gervase Peterson":           "November 2",
      "Tina Wesson":                "December 26",
      "Ciera Eastin":               "March 5",
      "Laura Morett":               "July 30",
      "Hayden Moss":                "May 27",
      "Katie Collins":              "June 27",
      "Caleb Bankston":             "March 26",
      "Vytas Baskauskas":           "December 8",
      "Aras Baskauskas":            "September 26",
      "Laura Boneham":              "August 29",
      "John Cody":                  "May 12",
      "Kat Edorsson":               "June 22",
      "Brad Culpepper":             "May 8",
      "Candice Cody":               "November 12",
      "Marissa Peterson":           "September 25",
      "Rachel Foulger":             "July 28",
      "Colton Cumbie":              "November 22",
      "Rupert Boneham":             "January 27"
    },
    "28":                           {
      "Tony Vlachos":               "September 10",
      "Woo Hwang":                  "March 16",
      "Kass McQuillen":             "November 8",
      "Spencer Bledsoe":            "June 12",
      "Trish Hegarty":              "October 9",
      "Tasha Fox":                  "January 3",
      "Jefra Bland":                "July 2",
      "Jeremiah Wood":              "June 15",
      "LJ McKanas":                 "January 8",
      "Morgan McLeod":              "July 9",
      "Sarah Lacina":               "July 9",
      "Alexis Maxwell":             "March 17",
      "Lindsey Ogle":               "September 4",
      "Cliff Robinson":             "December 16",
      "J'Tia Taylor":               "September 1",
      "Brice Johnston":             "February 20",
      "Garrett Adelstein":          "May 16",
      "David Samson":               "February 26"
    },
    "29":                           {
      "Natalie Anderson":           "April 11",
      "Jaclyn Schultz":             "August 16",
      "Missy Payne":                "June 10",
      "Keith Nale":                 "August 16",
      "Baylor Wilson":              "January 25",
      "Jon Misch":                  "March 29",
      "Alec Christy":               "September 7",
      "Reed Kelly":                 "September 5",
      "Wes Nale":                   "June 19",
      "Jeremy Collins":             "April 16",
      "Josh Canfield":              "July 1",
      "Julie McGee":                "January 24",
      "Dale Wentworth":             "March 7",
      "Kelley Wentworth":           "June 7",
      "Drew Christy":               "May 18",
      "John Rocker":                "October 17",
      "Val Collins":                "November 8",
      "Nadiya Anderson":            "April 11"
    },
    "30":                           {
      "Mike Holloway":              "July 25",
      "Will Sims II":               "August 13",
      "Carolyn Rivera":             "October 7",
      "Rodney Lavoie Jr.":          "September 2",
      "Sierra Dawn Thomas":         "December 18",
      "Dan Foley":                  "February 5",
      "Tyler Fredrickson":          "February 26",
      "Shirin Oskooi":              "February 25",
      "Jenn Brown":                 "January 27",
      "Joe Anglim":                 "September 30",
      "Hali Ford":                  "July 20",
      "Kelly Remington":            "April 27",
      "Joaquin Souberbielle":       "August 16",
      "Max Dawson":                 "March 31",
      "Lindsey Cascaddan":          "August 24",
      "Nina Poersch":               "January 17",
      "Vince Sly":                  "February 16",
      "So Kim":                     "January 13"
    },
    "31":                           {
      "Jeremy Collins":             "April 16",
      "Tasha Fox":                  "January 3",
      "Spencer Bledsoe":            "June 12",
      "Kelley Wentworth":           "June 7",
      "Keith Nale":                 "August 16",
      "Kimmi Kappenburg":           "November 11",
      "Abi-Maria Gomes":            "October 21",
      "Joe Anglim":                 "September 30",
      "Stephen Fishbach":           "January 24",
      "Ciera Eastin":               "March 5",
      "Kelly Wigglesworth":         "June 24",
      "Andrew Savage":              "July 29",
      "Kass McQuillen":             "November 8",
      "Woo Hwang":                  "March 16",
      "Terry Deitz":                "October 10",
      "Monica Padilla":             "July 14",
      "Jeff Varner":                "April 16",
      "Peih-Gee Law":               "April 7",
      "Shirin Oskooi":              "February 25",
      "Vytas Baskauskas":           "December 8"
    },
    "32":                           {
      "Michele Fitzgerald":         "May 5",
      "Aubry Bracco":               "November 14",
      "Tai Trang":                  "March 23",
      "Cydney Gillon":              "September 14",
      "Joe del Campo":              "July 4",
      "Kyle Jason":                 "July 16",
      "Julia Sokolowski":           "April 8",
      "Scot Pollard":               "February 12",
      "Debbie Wanner":              "November 21",
      "Nick Maiorano":              "January 28",
      "Neal Gottlieb":              "February 3",
      "Peter Baggenstos":           "July 21",
      "Anna Khait":                 "September 17",
      "Alecia Holden":              "August 3",
      "Caleb Reynolds":             "November 27",
      "Liz Markham":                "August 14",
      "Jennifer Lanzetti":          "July 14",
      "Darnell Hamilton":           "February 8"
    },
    "33":                           {
      "Adam Klein":                 "January 15",
      "Ken McNickle":               "September 20",
      "Hannah Shapiro":             "February 24",
      "David Wright":               "February 28",
      "Bret LaBelle":               "August 20",
      "Jay Starrett":               "June 3",
      "Sunday Burquest":            "February 6",
      "Will Wahl":                  "August 12",
      "Zeke Smith":                 "January 25",
      "Jessica Lewis":              "February 24",
      "Chris Hammons":              "April 1",
      "Taylor Stocker":             "November 20",
      "Michelle Schubert":          "March 11",
      "Michaela Bradshaw":          "December 1",
      "Figgy Figueroa":             "December 12",
      "CeCe Taylor":                "March 2",
      "Lucy Huang":                 "September 22",
      "Paul Wachter":               "October 10",
      "Mari Takahashi":             "November 2",
      "Rachel Ako":                 "September 8"
    },
    "34":                           {
      "Sarah Lacina":               "July 9",
      "Brad Culpepper":             "May 8",
      "Troyzan Robertson":          "July 30",
      "Tai Trang":                  "March 23",
      "Aubry Bracco":               "November 14",
      "Cirie Fields":               "July 18",
      "Andrea Boehlke":             "May 10",
      "Sierra Dawn Thomas":         "December 18",
      "Zeke Smith":                 "January 25",
      "Debbie Wanner":              "November 21",
      "Ozzy Lusth":                 "August 23",
      "Hali Ford":                  "July 20",
      "Jeff Varner":                "April 16",
      "Sandra Diaz-Twine":          "July 30",
      "J.T. Thomas":                "June 23",
      "Malcolm Freberg":            "May 7",
      "Caleb Reynolds":             "November 27",
      "Tony Vlachos":               "September 10",
      "Ciera Eastin":               "March 5"
    },
    "35":                           {
      "Ben Driebergen":             "January 1",
      "Chrissy Hofbeck":            "March 9",
      "Ryan Ulrich":                "September 8",
      "Devon Pinto":                "March 6",
      "Mike Zahalsky":              "September 11",
      "Ashley Nolan":               "September 17",
      "Lauren Rimmer":              "March 6",
      "Joe Mena":                   "March 15",
      "JP Hilsabeck":               "June 22",
      "Cole Medders":               "September 18",
      "Desi Williams":              "June 14",
      "Jessica Johnston":           "April 5",
      "Ali Elliott":                "November 13",
      "Roark Luskin":               "December 3",
      "Alan Ball":                  "March 29",
      "Patrick Bolton":             "March 6",
      "Simone Nguyen":              "May 31",
      "Katrina Radke":              "December 17"
    },
    "36":                           {
      "Wendell Holland":            "March 8",
      "Domenick Abbate":            "October 31",
      "Laurel Johnson":             "February 28",
      "Angela Perkins":             "November 2",
      "Donathan Hurley":            "July 19",
      "Sebastian Noel":             "July 20",
      "Kellyn Bechtold":            "November 1",
      "Chelsea Townsend":           "May 25",
      "Michael Yerger":             "July 20",
      "Jenna Bowman":               "November 10",
      "Desiree Afuye":              "February 3",
      "Libby Vincek":               "August 24",
      "Chris Noble":                "December 4",
      "Bradley Kleihege":           "September 14",
      "James Lim":                  "March 17",
      "Stephanie Johnson":          "September 10",
      "Brendan Shapiro":            "June 17",
      "Morgan Ricke":               "August 7",
      "Jacob Derwin":               "June 1",
      "Stephanie Gonzalez":         "April 22"
    }
  },
  "big_brother": {
    "1": {
      "Eddie McGee":          "February 24",
      "Josh Souza":           "February 21",
      "Curtis Kin":           "November 22",
      "Jamie Marie Kern":     "July 16",
      "George Allen Boswell": "September 29",
      "Cassandra Waldon":     "October 17",
      "Brittany Petros":      "September 9",
      "Karen Fowler":         "September 17",
      "Jean Jordan":          "August 2",
      "William Collins":      "August 14"
    },
    "2": {
      "Will Kirby":               "January 2",
      "Nicole Nilson Schaffrich": "February 3",
      "Monica Bailey":            "June 22",
      "Hardy Ames-Hill":          "May 12",
      "Bunky Miller":             "",
      "Krista Stegall":           "July 21",
      "Kent Blackwelder":         "March 1",
      "Mike Malin":               "July 16",
      "Shannon Dragoo":           "December 17",
      "Autumn Daly":              "December 11",
      "Sheryl Braxton":           "",
      "Justin Sebik":             "September 10"
    },
    "3": {
      "Lisa Donahue":       "February 4",
      "Danielle Reyes":     "January 22",
      "Jason Guy":          "June 22",
      "Amy Crews":          "June 11",
      "Marcellas Reynolds": "November 11",
      "Roddy Mancuso":      "May 18",
      "Gerry Lancaster":    "December 25",
      "Chiara Jude Berti":  "March 27",
      "Josh Feinberg":      "November 13",
      "Eric Ouellette":     "May 13",
      "Tonya Paoni":        "January 28",
      "Lori Olsen":         ""
    },
    "4": {
      "Jun Song":         "July 19",
      "Alison Irwin":     "August 7",
      "Robert Roman":     "November 12",
      "Erika Landin":     "December 5",
      "Jee Choe":         "",
      "Jack Owens, Jr":   "December 19",
      "Justin Giovinco":  "January 3",
      "Nathan Marlow":    "October 2",
      "Dana Varela":      "",
      "David Lane":       "",
      "Michelle Maradie": "",
      "Amanda Craig":     "",
      "Scott Weintraub":  ""
    },
    "5": {
      "Drew Daniel":     "April 28",
      "Michael Ellis":   "December 12",
      "Diane Henry":     "March 1",
      "Nakomis Dedmon":  "April 25",
      "Karen Ganci":     "January 17",
      "Marvin Latimer":  "",
      "Adria Klein":     "June 24",
      "Natalie Carroll": "June 24",
      "Will Wikle":      "December 15",
      "Jase Wirey":      "",
      "Scott Long":      "June 15",
      "Holly King":      "August 20",
      "Lori Valenti":    "November 16",
      "Mike Lubinski":   "March 8"
    },
    "6":{
      "Maggie Ausburn":    "August 14",
      "Ivette Corredero":  "February 9",
      "Janelle Pierzina":  "January 10",
      "April Lewis":       "July 29",
      "Howie Gordon":      "January 7",
      "Beau Beasley":      "December 11",
      "James Rhine":       "December 6",
      "Rachel Plencner":   "November 29",
      "Jennifer Vasquez":  "April 8",
      "Kaysar Ridha":      "August 10",
      "Sarah Hrejsa":      "July 24",
      "Eric Littmann":     "April 29",
      "Michael Donnellan": "December 5",
      "Ashlea Evans":      "April 24"
    },
    "7": {
      "Mike Malin":           "July 16",
      "Erika Landin":         "December 5",
      "Janelle Pierzina":     "January 10",
      "Will Kirby":           "January 2",
      "George Allen Boswell": "September 29",
      "Danielle Reyes":       "January 22",
      "James Rhine":          "December 6",
      "Howie Gordon":         "January 7",
      "Marcellas Reynolds":   "November 11",
      "Kaysar Ridha":         "August 10",
      "Diane Ogden":          "April 27",
      "Jase Wirey":           "",
      "Nakomis Dedmon":       "April 25",
      "Alison Irwin":         "August 7"
    },
    "8": {
      "Dick Donato":       "June 24",
      "Daniele Donato":    "August 20",
      "Zach Swerdzewki":   "April 17",
      "Jameka Cameron":    "July 20",
      "Eric Stein":        "January 25",
      "Jessica Hughbanks": "December 22",
      "Amber Siyavus":     "March 17",
      "Jen Johnson":       "April 25",
      "Dustin Erikstrup":  "January 21",
      "Kail Harbick":      "October 5",
      "Nick Starcevic":    "March 5",
      "Mike Dutz":         "August 20",
      "Joe Barber":        "September 28",
      "Carol Journey":     "March 3"
    },
    "9": {
      "Adam Jasinski":      "April 30",
      "Ryan Quicksall":     "September 16",
      "Sheila Kennedy":     "April 12",
      "Sharon Obermueller": "June 24",
      "Natalie Cunial":     "November 7",
      "James Zinkand":      "November 21",
      "Joshuah Welch":      "June 3",
      "Chelsia Hart":       "November 9",
      "Matt McDonald":      "April 7",
      "Allison Nichols":    "July 24",
      "Alex Coladonato":    "August 16",
      "Amanda Hansen":      "August 17",
      "Jen Diturno":        "October 18",
      "Parker Somerville":  "April 6",
      "Neil Garcia":        "September 16",
      "Jacob Heald":        "May 15"
    },
    "10": {
      "Dan Gheesling":   "September 1",
      "Memphis Garrett": "December 6",
      "Jerry MacDonald": "March 13",
      "Keesha Smith":    "August 8",
      "Renny Martyn":    "July 29",
      "Bryan Ollie":     "October 22",
      "Michelle Costa":  "December 29",
      "April Dowling":   "March 24",
      "Libra Thompson":  "August 6",
      "Jessie Godderz":  "April 23",
      "Angie Swindell":  "July 2",
      "Steven Daigle":   "May 24",
      "Brian Hart":      "August 21"
    },
    "11": {
      "Jordon Lloyd":     "November 21",
      "Natalie Martinez": "March 3",
      "Kevin Campbell":   "September 18",
      "Michele Noonan":   "June 16",
      "Jeff Schroeder":   "June 5",
      "Russell Kairouz":  "September 1",
      "Lydia Tavera":     "March 8",
      "Chima Simone":     "July 28",
      "Jessie Godderz":   "April 23",
      "Ronnie Talbott":   "January 15",
      "Casey Turner":     "February 16",
      "Laura Crosby":     "December 21",
      "Braden Bacha":     "September 13"
    },
    "12": {
      "Hayden Moss":       "May 21",
      "Lane Elenburg":     "October 10",
      "Enzo Palumbo":      "January 16",
      "Britney Haynes":    "August 23",
      "Ragan Fox":         "May 9",
      "Brendon Villegas":  "July 2",
      "Matt Hoffman":      "July 31",
      "Kathy Hillis":      "May 2",
      "Rachel Reilly":     "October 16",
      "Kristen Bitting":   "January 7",
      "Andrew Ian Gordon": "April 29",
      "Monet Stunson":     "September 4",
      "Annie Whittington": "March 13"
    },
    "13": {
      "Rachel Reilly":    "October 16",
      "Porsche Briggs":   "",
      "Adam Poch":        "August 7",
      "Jordon Lloyd":     "November 21",
      "Kalia Booker":     "",
      "Shelly Moore":     "",
      "Jeff Schroeder":   "June 5",
      "Daniele Donato":   "August 20",
      "Brendon Villegas": "July 2",
      "Lawon Exum":       "",
      "Dominic Briones":  "",
      "Cassi Colvin":     "",
      "Keith Henderson":  "",
      "Dick Donato":      "June 24",
    },
    "14": {
      "Ian Terry":         "March 19",
      "Dan Gheesling":     "September 1",
      "Danielle Murphree": "April 23",
      "Shane Meaney":      "December 9",
      "Jenn Arroyo":       "March 20",
      "Joe Arvin":         "April 16",
      "Frank Eudy":        "April 24",
      "Britney Haynes":    "August 23",
      "Ashley Iocco":      "October 30",
      "Mike Malin":        "July 16",
      "Wil Heuser":        "July 29",
      "Janelle Pierzina":  "January 10",
      "JoJo Spatafora":    "August 21",
      "Willie Hantz":      "October 17",
      "Kara Monaco":       "March 27",
      "Jodi Rollins":      ""
    },
    "15": {
      "Andy Herren":         "November 14",
      "GinaMarie Zimmerman": "August 22",
      "Spencer Clawson":     "February 16",
      "McCrae Olsen":        "July 21",
      "Judd Daugherty":      "December 26",
      "Elissa Slater":       "February 9",
      "Amanda Zuckerman":    "May 11",
      "Aaryn Gries":         "September 3",
      "Helen Kim":           "May 6",
      "Jessie Kowalski":     "May 16",
      "Candice Stewart":     "September 19",
      "Howard Overby":       "September 3",
      "Kaitlin Barnaby":     "February 19",
      "Jeremy McGuire":      "November 29",
      "Nick Uhas":           "March 30",
      "David Girton":        "January 22"
    },
    "16": {
      "Derrick Levasseur": "March 3",
      "Cody Calafiore":    "December 13",
      "Victoria Rafaeli":  "June 16",
      "Caleb Reynolds":    "November 27",
      "Frankie Grande":    "January 24",
      "Christine Brecht":  "May 8",
      "Nicole Franzel":    "June 30",
      "Donny Thompson":    "December 7",
      "Zach Rance":        "September 9",
      "Hayden Voss":       "June 8",
      "Jocasta Odom":      "August 10",
      "Amber Borzotra":    "January 13",
      "Brittany Martinez": "February 1",
      "Devin Shepherd":    "September 9",
      "Paola Shea":        "May 29",
      "Joey Van Pelt":     "February 7"
    },
    "17": {
      "Steve Moses":      "December 10",
      "Liz Nolan":        "December 23",
      "Vanessa Rousso":   "February 5",
      "Austin Matelson":  "March 10",
      "Julia Nolan":      "December 23",
      "James Huling":     "May 22",
      "Meg Maley":        "January 17",
      "Becky Burgess":    "May 6",
      "Jackie Ibarra":    "October 24",
      "Shelli Poole":     "January 12",
      "Clay Honeycutt":   "March 12",
      "Jason Roy":        "August 13",
      "Audrey Middleton": "February 8",
      "Jeff Weldon":      "June 21",
      "Da'Vonne Rogers":  "May 10",
      "Jace Agolli":      "December 8"
    },
    "18": {
      "Nicole Franzel":    "June 30",
      "Paul Abrahamian":   "June 13",
      "James Huling":      "May 22",
      "Corey Brooks":      "October 31",
      "Victor Arroyo":     "April 20",
      "Natalie Negrotti":  "March 22",
      "Michelle Meyer":    "December 26",
      "Paulie Calafiore":  "December 13",
      "Bridgette Dunning": "July 15",
      "Zakiyah Everette":  "July 11",
      "Da'Vonne Rogers":   "May 10",
      "Frank Eudy":        "April 24",
      "Tiffany Rousso":    "April 19",
      "Bronte D'Acquisto": "",
      "Jozea Flores":      "February 26",
      "Glenn Garcia":      ""
    },
    "19": {
      "Josh Martinez":    "January 4",
      "Paul Abrahamian":  "June 13",
      "Christmas Abbott": "December 20",
      "Kevin Schlehuber": "August 7",
      "Alex Ow":          "December 20",
      "Raven Walton":     "June 10",
      "Jason Dent":       "July 12",
      "Matthew Clines":   "March 31",
      "Mark Jansen":      "June 13",
      "Elena Davies":     "August 19",
      "Cody Nickson":     "April 13",
      "Jessica Graf":     "December 11",
      "Ramses Soto":      "December 18",
      "Dominique Cooper": "July 11",
      "Jillian Parker":   "May 12",
      "Megan Lowder":     "March 7",
      "Cameron Heard":    "August 27"
    },
    "20": {
      "Tyler Crispen":    "February 18",
      "Angela Rummans":   "March 23",
      "Brett Robinson":   "",
      "Kaycee Clark":     "December 26",
      "JC Mounduix":      "February 6",
      "Sam Bledsoe":      "June 7",
      "Haleigh Broucher": "January 23",
      "Faysal Shafaat":   "October 17",
      "Scottie Salton":   "January 10",
      "Rockstar":         "June 22",
      "Bayleigh Dayton":  "May 25",
      "Rachel Swindler":  "July 15",
      "Kaitlyn Herman":   "April 24",
      "Winston Hines":    "February 13",
      "Swaggy-C":         "February 17",
      "Steve Arienta":    "May 2"
    }
  }
}

survivor_hash = contestants[:survivor]
survivor_hash.keys.each_with_index do |season, index|
  survivor_hash[season].each_with_index do |player, i|
    contestant = Contestant.find_or_create_by(name: player.first, birthday: player.last)
    survivor_contestant = SurvivorContestant.find_or_create_by(contestant: contestant,
                                                               season: Season.where(
                                                                 television_show: survivor,
                                                                 season_number: index + 1).first)
    survivor_contestant.update_attributes(place: i+1)
  end
end

big_brother_hash = contestants[:big_brother]
big_brother_hash.keys.each_with_index do |season, index|
  big_brother_hash[season].each do |player|
    contestant = Contestant.find_or_create_by(name: player.first, birthday: player.last)
    BigBrotherContestant.find_or_create_by(contestant: contestant,
                                           season: Season.where(
                                             television_show: big_brother.id,
                                             season_number: index + 1).first)
  end
end
